### ISSUE TITLE
cln-ntfy seems to not be compatible with cln-plugin-0.1.4

### ISSUE THREAD

**Issue by bitcoinlizard** [yukibtc/cln-ntfy#10]
I receive these errors when trying to create an invoice or pay an invoice, no NTFY notification is sent:

invoice created:
```
Jan 28 15:50:10 bitcoin lightningd[95628]: thread 'tokio-runtime-worker' panicked at /home/bitcoin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cln-plugin-0.1.4/src/lib.rs:623:62:
Jan 28 15:50:10 bitcoin lightningd[95628]: called `Result::unwrap()` on an `Err` value: invalid type: null, expected a string
Jan 28 15:50:10 bitcoin lightningd[95628]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

invoice paid:
```
Jan 28 15:51:54 bitcoin lightningd[95628]: thread 'tokio-runtime-worker' panicked at /home/bitcoin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cln-plugin-0.1.4/src/lib.rs:623:62:
Jan 28 15:51:54 bitcoin lightningd[95628]: called `Result::unwrap()` on an `Err` value: invalid type: integer `203000`, expected a string
```

**Comment by bitcoinlizard** [comment]
This seems to be the same issue:
https://github.com/ElementsProject/lightning/issues/6626

There is a pull request so maybe the problem with cln-ntfy will be resolved when this pull request is merged.
